services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nukta_print
    ports:
      - "5433:5432"
    volumes:
      - nukta_pgdata:/var/lib/postgresql/data

volumes:
  nukta_pgdata:
