import type { ProductWithIncludes } from '@/types/prisma'

export type CatalogProduct = ProductWithIncludes & {
   variants?: Array<{
      id: string
      name: string
      value: string
      priceModifier: number
      productId: string
   }>
}

export const DUMMY_BRANDS = [
   { id: 'brand-fannify', title: 'Fannify', description: 'House brand', logo: null },
   { id: 'brand-studio', title: 'Studio Print', description: 'Premium blanks', logo: null },
]

export const DUMMY_CATEGORIES = [
   { id: 'cat-apparel', title: 'Apparel', description: 'T-shirts, hoodies, pants & more' },
   { id: 'cat-bags', title: 'Bags', description: 'Totes, backpacks & packaging' },
   { id: 'cat-drinkware', title: 'Drinkware', description: 'Mugs and bottles' },
   { id: 'cat-packaging', title: 'Packaging', description: 'Mailers, stickers & labels' },
   { id: 'cat-accessories', title: 'Accessories', description: 'Caps, posters & more' },
   { id: 'cat-home', title: 'Home & Office', description: 'Posters and desk items' },
]

const img = (id: string) =>
   `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`

function variants(
   productId: string,
   groups: Record<string, { values: string[]; modifiers?: number[] }>
) {
   const rows: CatalogProduct['variants'] = []
   for (const [name, config] of Object.entries(groups)) {
      config.values.forEach((value, index) => {
         rows!.push({
            id: `${productId}-${name}-${value}`.toLowerCase().replace(/\s+/g, '-'),
            name,
            value,
            priceModifier: config.modifiers?.[index] ?? 0,
            productId,
         })
      })
   }
   return rows
}

export const DUMMY_PRODUCTS: CatalogProduct[] = [
   {
      id: 'classic-crew-tee',
      title: 'Classic Crew T-Shirt',
      description:
         'Soft ring-spun cotton tee. Ideal for screen print, DTG, and heat transfer. Unisex fit with reinforced neckline.',
      images: [
         img('photo-1521572163474-6864f9cf17ab'),
         img('photo-1583743814966-8936f5b7be1a'),
         img('photo-1576566588028-4147f3842f27'),
      ],
      keywords: ['t-shirt', 'apparel', 'cotton', 'custom'],
      metadata: {
         productType: 'T-Shirts',
         isCustomizable: true,
         material: '100% Cotton',
         printAreas: ['Front', 'Back', 'Sleeve'],
         leadTimeDays: 3,
      },
      price: 14.99,
      discount: 2,
      stock: 500,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('classic-crew-tee', {
         Size: { values: ['S', 'M', 'L', 'XL', '2XL'], modifiers: [0, 0, 0, 2, 4] },
         Color: { values: ['White', 'Black', 'Navy', 'Heather Grey'], modifiers: [0, 0, 1, 1] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'premium-tee',
      title: 'Premium Soft Tee',
      description: 'Heavier fabric with retail-quality hand feel. Bestseller for brand merch and events.',
      images: [img('photo-1618354691373-d851fcf5c3b0'), img('photo-1622445265470-35b2494dd58e')],
      keywords: ['premium', 'tee'],
      metadata: { productType: 'T-Shirts', isCustomizable: true, material: 'Cotton blend', leadTimeDays: 4 },
      price: 19.99,
      discount: 0,
      stock: 300,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('premium-tee', {
         Size: { values: ['S', 'M', 'L', 'XL'] },
         Color: { values: ['White', 'Black', 'Sand'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'pullover-hoodie',
      title: 'Pullover Hoodie',
      description: 'Mid-weight fleece hoodie with kangaroo pocket. Perfect for embroidery and large front prints.',
      images: [img('photo-1556821840-3a63f95609a7'), img('photo-1620799140408-f9f8e7b7ecb1')],
      keywords: ['hoodie', 'fleece'],
      metadata: { productType: 'Hoodies', isCustomizable: true, material: 'Fleece', leadTimeDays: 5 },
      price: 34.99,
      discount: 5,
      stock: 200,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('pullover-hoodie', {
         Size: { values: ['S', 'M', 'L', 'XL', '2XL'], modifiers: [0, 0, 0, 3, 5] },
         Color: { values: ['Black', 'Grey', 'Navy', 'Maroon'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'jogger-pants',
      title: 'Unisex Jogger Pants',
      description: 'Tapered fit joggers with elastic cuffs. Comfortable everyday wear with full leg branding space.',
      images: [img('photo-1544966503-7cc5ac882d5f'), img('photo-1506629082955-511b05f03b55')],
      keywords: ['pants', 'joggers'],
      metadata: { productType: 'Pants', isCustomizable: true, material: 'Poly cotton', leadTimeDays: 5 },
      price: 29.99,
      discount: 0,
      stock: 150,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('jogger-pants', {
         Size: { values: ['S', 'M', 'L', 'XL'] },
         Color: { values: ['Black', 'Charcoal', 'Olive'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'leggings',
      title: 'All-Over Print Leggings',
      description: 'Stretch leggings for all-over sublimation. Bold patterns and brand storytelling.',
      images: [img('photo-1506629082955-511b05f03b55'), img('photo-1544966503-7cc5ac882d5f')],
      keywords: ['leggings', 'sublimation'],
      metadata: { productType: 'Pants', isCustomizable: true, leadTimeDays: 6 },
      price: 24.99,
      discount: 0,
      stock: 120,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('leggings', {
         Size: { values: ['XS', 'S', 'M', 'L', 'XL'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'canvas-tote',
      title: 'Canvas Tote Bag',
      description: '12oz canvas tote with long handles. Eco-friendly merch and event giveaways.',
      images: [img('photo-1590874103328-eac38a683ce7'), img('photo-1548036328-c9fa89d128fa')],
      keywords: ['tote', 'bag'],
      metadata: { productType: 'Bags', isCustomizable: true, leadTimeDays: 4 },
      price: 11.99,
      discount: 0,
      stock: 400,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[1] as any],
      variants: variants('canvas-tote', {
         Color: { values: ['Natural', 'Black', 'Navy'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'drawstring-bag',
      title: 'Drawstring Backpack',
      description: 'Lightweight polyester drawstring bag for gyms, schools, and promo drops.',
      images: [img('photo-1553062407-98eeb64c6a62')],
      keywords: ['backpack', 'drawstring'],
      metadata: { productType: 'Bags', isCustomizable: true, leadTimeDays: 3 },
      price: 8.99,
      discount: 0,
      stock: 600,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[1] as any],
      variants: variants('drawstring-bag', {
         Color: { values: ['White', 'Black', 'Royal Blue', 'Red'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'mailer-box',
      title: 'Branded Mailer Box',
      description: 'Rigid mailer for ecommerce unboxing. Full-color exterior print with custom sizing.',
      images: [img('photo-1558618666-fcd25c85cd64')],
      keywords: ['packaging', 'mailer'],
      metadata: { productType: 'Packaging', isCustomizable: true, leadTimeDays: 7 },
      price: 2.49,
      discount: 0,
      stock: 1000,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[2] as any],
      variants: variants('mailer-box', {
         Size: { values: ['Small', 'Medium', 'Large'], modifiers: [0, 1.5, 3] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'sticker-pack',
      title: 'Die-Cut Sticker Sheet',
      description: 'Weather-resistant vinyl stickers. Sold per sheet with multiple shapes.',
      images: [img('photo-1586075010923-aa2a337b7c52')],
      keywords: ['stickers', 'vinyl'],
      metadata: { productType: 'Packaging', isCustomizable: true, leadTimeDays: 2 },
      price: 4.99,
      discount: 0,
      stock: 800,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[2] as any],
      variants: variants('sticker-pack', {
         Finish: { values: ['Matte', 'Gloss'], modifiers: [0, 0.5] },
         Size: { values: ['3×3 in', '4×4 in'], modifiers: [0, 1] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'ceramic-mug',
      title: 'Ceramic Mug 11oz',
      description: 'Dishwasher-safe mug with wrap or single-side print. Great for corporate gifts.',
      images: [img('photo-1514228742587-6b1558fcca3e')],
      keywords: ['mug', 'drinkware'],
      metadata: { productType: 'Drinkware', isCustomizable: true, leadTimeDays: 4 },
      price: 9.99,
      discount: 1,
      stock: 350,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[2] as any],
      variants: variants('ceramic-mug', {
         Color: { values: ['White', 'Black'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'poster-print',
      title: 'Premium Poster Print',
      description: 'Museum-quality poster on premium paper. Available in standard frame sizes.',
      images: [img('photo-1513475382585-d06e58bcb0e6')],
      keywords: ['poster', 'print'],
      metadata: { productType: 'Home & Office', isCustomizable: true, leadTimeDays: 3 },
      price: 12.99,
      discount: 0,
      stock: 250,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[5] as any],
      variants: variants('poster-print', {
         Size: { values: ['12×18 in', '18×24 in', '24×36 in'], modifiers: [0, 4, 8] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'baseball-cap',
      title: 'Structured Baseball Cap',
      description: 'Six-panel cap with embroidery-ready front panel and adjustable strap.',
      images: [img('photo-1588850561407-ed78c282e68b')],
      keywords: ['cap', 'hat'],
      metadata: { productType: 'Accessories', isCustomizable: true, leadTimeDays: 5 },
      price: 16.99,
      discount: 0,
      stock: 180,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[4] as any],
      variants: variants('baseball-cap', {
         Color: { values: ['Black', 'Navy', 'Khaki', 'White'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'tank-top',
      title: 'Performance Tank Top',
      description: 'Moisture-wicking tank for gyms and sports brands. Lightweight and breathable.',
      images: [img('photo-1571019613454-1cb2f99b2d8b')],
      keywords: ['tank', 'sport'],
      metadata: { productType: 'T-Shirts', isCustomizable: true, leadTimeDays: 4 },
      price: 13.99,
      discount: 0,
      stock: 220,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('tank-top', {
         Size: { values: ['S', 'M', 'L', 'XL'] },
         Color: { values: ['White', 'Black', 'Red'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'polo-shirt',
      title: 'Classic Polo Shirt',
      description: 'Business-ready polo with side seams. Embroidery-friendly collar and cuffs.',
      images: [img('photo-1620799140408-f9f8e7b7ecb1')],
      keywords: ['polo', 'corporate'],
      metadata: { productType: 'T-Shirts', isCustomizable: true, leadTimeDays: 5 },
      price: 22.99,
      discount: 3,
      stock: 140,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('polo-shirt', {
         Size: { values: ['S', 'M', 'L', 'XL', '2XL'] },
         Color: { values: ['White', 'Navy', 'Black'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'sweatpants',
      title: 'Fleece Sweatpants',
      description: 'Relaxed fleece sweatpants with drawcord waist. Cozy merch staple.',
      images: [img('photo-1544966503-7cc5ac882d5f')],
      keywords: ['sweatpants', 'fleece'],
      metadata: { productType: 'Pants', isCustomizable: true, leadTimeDays: 5 },
      price: 27.99,
      discount: 0,
      stock: 90,
      isPhysical: true,
      isAvailable: false,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('sweatpants', {
         Size: { values: ['S', 'M', 'L', 'XL'] },
         Color: { values: ['Grey', 'Black'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
]

export const DUMMY_PRODUCT_TYPES = [
   'T-Shirts',
   'Hoodies',
   'Pants',
   'Bags',
   'Packaging',
   'Drinkware',
   'Accessories',
   'Home & Office',
] as const
