import { CATALOG_IMAGES } from '@/lib/catalog-images'
import type { ProductWithIncludes } from '@/types/prisma'

export type CatalogProduct = ProductWithIncludes & {
   variants?: Array<{
      id: string
      name: string
      value: string
      priceModifier: number
      productId: string
   }>
}

export const DUMMY_BRANDS = [
   { id: 'brand-fannify', title: 'Fannify', description: 'House brand', logo: null },
   { id: 'brand-studio', title: 'Studio Print', description: 'Premium blanks', logo: null },
]

export const DUMMY_CATEGORIES = [
   { id: 'cat-fastfood', title: 'Fast Food Packaging', description: 'Pizza boxes, burger boxes & takeout packs' },
   { id: 'cat-apparel', title: 'Apparel', description: 'T-shirts, hoodies, pants & more' },
   { id: 'cat-bags', title: 'Bags', description: 'Totes, backpacks & packaging' },
   { id: 'cat-drinkware', title: 'Drinkware', description: 'Mugs and bottles' },
   { id: 'cat-packaging', title: 'Packaging', description: 'Mailers, stickers & labels' },
   { id: 'cat-accessories', title: 'Accessories', description: 'Caps, posters & more' },
   { id: 'cat-home', title: 'Home & Office', description: 'Posters and desk items' },
]

function variants(
   productId: string,
   groups: Record<string, { values: string[]; modifiers?: number[] }>
) {
   const rows: CatalogProduct['variants'] = []
   for (const [name, config] of Object.entries(groups)) {
      config.values.forEach((value, index) => {
         rows!.push({
            id: `${productId}-${name}-${value}`.toLowerCase().replace(/\s+/g, '-'),
            name,
            value,
            priceModifier: config.modifiers?.[index] ?? 0,
            productId,
         })
      })
   }
   return rows
}

export const DUMMY_PRODUCTS: CatalogProduct[] = [
   {
      id: 'classic-crew-tee',
      title: 'Classic Crew T-Shirt',
      description:
         'Soft ring-spun cotton tee. Ideal for screen print, DTG, and heat transfer. Unisex fit with reinforced neckline.',
      images: [CATALOG_IMAGES.teeWhite, CATALOG_IMAGES.teeStack, CATALOG_IMAGES.teeHanger],
      keywords: ['t-shirt', 'apparel', 'cotton', 'custom'],
      metadata: {
         productType: 'T-Shirts',
         isCustomizable: true,
         material: '100% Cotton',
         printAreas: ['Front', 'Back', 'Sleeve'],
         leadTimeDays: 3,
      },
      price: 14.99,
      discount: 2,
      stock: 500,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[1] as any],
      variants: variants('classic-crew-tee', {
         Size: { values: ['S', 'M', 'L', 'XL', '2XL'], modifiers: [0, 0, 0, 2, 4] },
         Color: { values: ['White', 'Black', 'Navy', 'Heather Grey'], modifiers: [0, 0, 1, 1] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'premium-tee',
      title: 'Premium Soft Tee',
      description: 'Heavier fabric with retail-quality hand feel. Bestseller for brand merch and events.',
      images: [CATALOG_IMAGES.teeFolded, CATALOG_IMAGES.teeStack],
      keywords: ['premium', 'tee'],
      metadata: { productType: 'T-Shirts', isCustomizable: true, material: 'Cotton blend', leadTimeDays: 4 },
      price: 19.99,
      discount: 0,
      stock: 300,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[1] as any],
      variants: variants('premium-tee', {
         Size: { values: ['S', 'M', 'L', 'XL'] },
         Color: { values: ['White', 'Black', 'Sand'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'pullover-hoodie',
      title: 'Pullover Hoodie',
      description: 'Mid-weight fleece hoodie with kangaroo pocket. Perfect for embroidery and large front prints.',
      images: [CATALOG_IMAGES.hoodie, CATALOG_IMAGES.sweatshirt],
      keywords: ['hoodie', 'fleece'],
      metadata: { productType: 'Hoodies', isCustomizable: true, material: 'Fleece', leadTimeDays: 5 },
      price: 34.99,
      discount: 5,
      stock: 200,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[1] as any],
      variants: variants('pullover-hoodie', {
         Size: { values: ['S', 'M', 'L', 'XL', '2XL'], modifiers: [0, 0, 0, 3, 5] },
         Color: { values: ['Black', 'Grey', 'Navy', 'Maroon'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'jogger-pants',
      title: 'Unisex Jogger Pants',
      description: 'Tapered fit joggers with elastic cuffs. Comfortable everyday wear with full leg branding space.',
      images: [CATALOG_IMAGES.pants, CATALOG_IMAGES.leggings],
      keywords: ['pants', 'joggers'],
      metadata: { productType: 'Pants', isCustomizable: true, material: 'Poly cotton', leadTimeDays: 5 },
      price: 29.99,
      discount: 0,
      stock: 150,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[1] as any],
      variants: variants('jogger-pants', {
         Size: { values: ['S', 'M', 'L', 'XL'] },
         Color: { values: ['Black', 'Charcoal', 'Olive'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'leggings',
      title: 'All-Over Print Leggings',
      description: 'Stretch leggings for all-over sublimation. Bold patterns and brand storytelling.',
      images: [CATALOG_IMAGES.leggings, CATALOG_IMAGES.pants],
      keywords: ['leggings', 'sublimation'],
      metadata: { productType: 'Pants', isCustomizable: true, leadTimeDays: 6 },
      price: 24.99,
      discount: 0,
      stock: 120,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[1] as any],
      variants: variants('leggings', {
         Size: { values: ['XS', 'S', 'M', 'L', 'XL'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'canvas-tote',
      title: 'Canvas Tote Bag',
      description: '12oz canvas tote with long handles. Eco-friendly merch and event giveaways.',
      images: [CATALOG_IMAGES.tote, CATALOG_IMAGES.bag],
      keywords: ['tote', 'bag'],
      metadata: { productType: 'Bags', isCustomizable: true, leadTimeDays: 4 },
      price: 11.99,
      discount: 0,
      stock: 400,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[2] as any],
      variants: variants('canvas-tote', {
         Color: { values: ['Natural', 'Black', 'Navy'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'drawstring-bag',
      title: 'Drawstring Backpack',
      description: 'Lightweight polyester drawstring bag for gyms, schools, and promo drops.',
      images: [CATALOG_IMAGES.backpack],
      keywords: ['backpack', 'drawstring'],
      metadata: { productType: 'Bags', isCustomizable: true, leadTimeDays: 3 },
      price: 8.99,
      discount: 0,
      stock: 600,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[2] as any],
      variants: variants('drawstring-bag', {
         Color: { values: ['White', 'Black', 'Royal Blue', 'Red'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'mailer-box',
      title: 'Branded Mailer Box',
      description: 'Rigid mailer for ecommerce unboxing. Full-color exterior print with custom sizing.',
      images: [CATALOG_IMAGES.mailer, CATALOG_IMAGES.product],
      keywords: ['packaging', 'mailer'],
      metadata: { productType: 'Packaging', isCustomizable: true, leadTimeDays: 7 },
      price: 2.49,
      discount: 0,
      stock: 1000,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[4] as any],
      variants: variants('mailer-box', {
         Size: { values: ['Small', 'Medium', 'Large'], modifiers: [0, 1.5, 3] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'sticker-pack',
      title: 'Die-Cut Sticker Sheet',
      description: 'Weather-resistant vinyl stickers. Sold per sheet with multiple shapes.',
      images: [CATALOG_IMAGES.sticker, CATALOG_IMAGES.product],
      keywords: ['stickers', 'vinyl'],
      metadata: { productType: 'Packaging', isCustomizable: true, leadTimeDays: 2 },
      price: 4.99,
      discount: 0,
      stock: 800,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[4] as any],
      variants: variants('sticker-pack', {
         Finish: { values: ['Matte', 'Gloss'], modifiers: [0, 0.5] },
         Size: { values: ['3×3 in', '4×4 in'], modifiers: [0, 1] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'ceramic-mug',
      title: 'Ceramic Mug 11oz',
      description: 'Dishwasher-safe mug with wrap or single-side print. Great for corporate gifts.',
      images: [CATALOG_IMAGES.mug, CATALOG_IMAGES.coffee],
      keywords: ['mug', 'drinkware'],
      metadata: { productType: 'Drinkware', isCustomizable: true, leadTimeDays: 4 },
      price: 9.99,
      discount: 1,
      stock: 350,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[3] as any],
      variants: variants('ceramic-mug', {
         Color: { values: ['White', 'Black'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'poster-print',
      title: 'Premium Poster Print',
      description: 'Museum-quality poster on premium paper. Available in standard frame sizes.',
      images: [CATALOG_IMAGES.sticker, CATALOG_IMAGES.product],
      keywords: ['poster', 'print'],
      metadata: { productType: 'Home & Office', isCustomizable: true, leadTimeDays: 3 },
      price: 12.99,
      discount: 0,
      stock: 250,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[6] as any],
      variants: variants('poster-print', {
         Size: { values: ['12×18 in', '18×24 in', '24×36 in'], modifiers: [0, 4, 8] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'baseball-cap',
      title: 'Structured Baseball Cap',
      description: 'Six-panel cap with embroidery-ready front panel and adjustable strap.',
      images: [CATALOG_IMAGES.cap],
      keywords: ['cap', 'hat'],
      metadata: { productType: 'Accessories', isCustomizable: true, leadTimeDays: 5 },
      price: 16.99,
      discount: 0,
      stock: 180,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[5] as any],
      variants: variants('baseball-cap', {
         Color: { values: ['Black', 'Navy', 'Khaki', 'White'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'tank-top',
      title: 'Performance Tank Top',
      description: 'Moisture-wicking tank for gyms and sports brands. Lightweight and breathable.',
      images: [CATALOG_IMAGES.tank],
      keywords: ['tank', 'sport'],
      metadata: { productType: 'T-Shirts', isCustomizable: true, leadTimeDays: 4 },
      price: 13.99,
      discount: 0,
      stock: 220,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[1] as any],
      variants: variants('tank-top', {
         Size: { values: ['S', 'M', 'L', 'XL'] },
         Color: { values: ['White', 'Black', 'Red'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'polo-shirt',
      title: 'Classic Polo Shirt',
      description: 'Business-ready polo with side seams. Embroidery-friendly collar and cuffs.',
      images: [CATALOG_IMAGES.polo, CATALOG_IMAGES.teeFolded],
      keywords: ['polo', 'corporate'],
      metadata: { productType: 'T-Shirts', isCustomizable: true, leadTimeDays: 5 },
      price: 22.99,
      discount: 3,
      stock: 140,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[1] as any],
      variants: variants('polo-shirt', {
         Size: { values: ['S', 'M', 'L', 'XL', '2XL'] },
         Color: { values: ['White', 'Navy', 'Black'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'sweatpants',
      title: 'Fleece Sweatpants',
      description: 'Relaxed fleece sweatpants with drawcord waist. Cozy merch staple.',
      images: [CATALOG_IMAGES.sweatshirt, CATALOG_IMAGES.pants],
      keywords: ['sweatpants', 'fleece'],
      metadata: { productType: 'Pants', isCustomizable: true, leadTimeDays: 5 },
      price: 27.99,
      discount: 0,
      stock: 90,
      isPhysical: true,
      isAvailable: false,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[1] as any],
      variants: variants('sweatpants', {
         Size: { values: ['S', 'M', 'L', 'XL'] },
         Color: { values: ['Grey', 'Black'] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'custom-pizza-box',
      title: 'Custom Pizza Box',
      description:
         'Grease-resistant corrugated pizza boxes with full-color lid print. Perfect for pizzerias, cloud kitchens, and delivery brands.',
      images: [CATALOG_IMAGES.customBoxLarge, CATALOG_IMAGES.customPackagingHero],
      keywords: ['pizza box', 'takeout', 'fast food', 'packaging'],
      metadata: {
         productType: 'Fast Food Packaging',
         isCustomizable: true,
         material: 'Corrugated board',
         printAreas: ['Lid', 'Sides'],
         leadTimeDays: 5,
      },
      price: 0.89,
      discount: 0,
      stock: 5000,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('custom-pizza-box', {
         Size: { values: ['10"', '12"', '14"', '16"'], modifiers: [0, 0.15, 0.3, 0.45] },
         Finish: { values: ['Kraft', 'White'], modifiers: [0, 0.08] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'burger-box',
      title: 'Branded Burger Box',
      description:
         'Fold-top burger clamshell with custom logo print. Food-safe coating for hot sandwiches and combo meals.',
      images: [CATALOG_IMAGES.customBoxMedium, CATALOG_IMAGES.customBoxLarge],
      keywords: ['burger box', 'clamshell', 'fast food'],
      metadata: {
         productType: 'Fast Food Packaging',
         isCustomizable: true,
         material: 'Food-grade paperboard',
         leadTimeDays: 4,
      },
      price: 0.42,
      discount: 0,
      stock: 8000,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('burger-box', {
         Size: { values: ['Standard', 'Large'], modifiers: [0, 0.12] },
         Color: { values: ['Kraft', 'White'], modifiers: [0, 0.06] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'fries-carton',
      title: 'Fries & Nugget Carton',
      description:
         'Open-top carton for fries, nuggets, and sides. Bold branding on all four panels.',
      images: [CATALOG_IMAGES.customBoxSmall, CATALOG_IMAGES.customBoxMedium],
      keywords: ['fries box', 'nugget carton', 'sides packaging'],
      metadata: { productType: 'Fast Food Packaging', isCustomizable: true, leadTimeDays: 3 },
      price: 0.28,
      discount: 0,
      stock: 10000,
      isPhysical: true,
      isAvailable: true,
      isFeatured: true,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('fries-carton', {
         Size: { values: ['Small', 'Medium', 'Large'], modifiers: [0, 0.05, 0.1] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'meal-tray-lid',
      title: 'Kraft Meal Tray with Lid',
      description:
         'Compartment meal tray for rice bowls, combos, and catering. Custom print on lid and sleeve band.',
      images: [CATALOG_IMAGES.customPackagingHero, CATALOG_IMAGES.customPaperBag],
      keywords: ['meal tray', 'takeout', 'combo box'],
      metadata: { productType: 'Fast Food Packaging', isCustomizable: true, leadTimeDays: 5 },
      price: 0.65,
      discount: 0,
      stock: 6000,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('meal-tray-lid', {
         Size: { values: ['1-compartment', '3-compartment'], modifiers: [0, 0.2] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'takeout-bag',
      title: 'Grease-Resistant Takeout Bag',
      description:
         'Twisted-handle paper bag for burgers, boxes, and combo orders. Full-color front and back print.',
      images: [CATALOG_IMAGES.customPaperBag, CATALOG_IMAGES.mailer],
      keywords: ['takeout bag', 'paper bag', 'delivery'],
      metadata: { productType: 'Fast Food Packaging', isCustomizable: true, leadTimeDays: 4 },
      price: 0.35,
      discount: 0,
      stock: 12000,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-studio',
      brand: DUMMY_BRANDS[1] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('takeout-bag', {
         Size: { values: ['Small', 'Medium', 'Large'], modifiers: [0, 0.08, 0.15] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
   {
      id: 'cup-carrier',
      title: '4-Cup Drink Carrier',
      description:
         'Sturdy drink carrier for delivery and counter pickup. Print your logo on all sides.',
      images: [CATALOG_IMAGES.customBoxSmall, CATALOG_IMAGES.customPaperBag],
      keywords: ['cup carrier', 'drink holder', 'delivery'],
      metadata: { productType: 'Fast Food Packaging', isCustomizable: true, leadTimeDays: 3 },
      price: 0.52,
      discount: 0,
      stock: 7000,
      isPhysical: true,
      isAvailable: true,
      isFeatured: false,
      brandId: 'brand-fannify',
      brand: DUMMY_BRANDS[0] as any,
      categories: [DUMMY_CATEGORIES[0] as any],
      variants: variants('cup-carrier', {
         Size: { values: ['2-cup', '4-cup'], modifiers: [0, 0.18] },
      }),
      createdAt: new Date(),
      updatedAt: new Date(),
   },
]

export const DUMMY_PRODUCT_TYPES = [
   'Fast Food Packaging',
   'T-Shirts',
   'Hoodies',
   'Pants',
   'Bags',
   'Packaging',
   'Drinkware',
   'Accessories',
   'Home & Office',
] as const
